const gUsrJson = 
{
    "ID": "admin",
    "Locale": "zz",
    "ScreenWidth": 0,
    "Page": "pk",
    "Rank": "EMU",
    "Prog": "100%",
    "Fuel": "100",
    "Level": "9999(⊇Svip)",
    "SVip": "SVIP：365天",
    "BVip": "BVIP：365天",
    "Coin1": " - ",
    "Coin2": " - ",
    "Coin3": " - ",
    "Cost": "0",
    "NpcLv": "+33%",
    "AssetRoot": "demo/game-icons/",
    "ActorDir": "actor/",
    "ActorMap": {
        "Z.": "",
        ".Z": ".png",
        "N.": "",
        ".N": ".png",
        "L.": "",
        ".L": ".png",
        "R.": "",
        ".R": ".png",
        "3901": "animal-hide",
        "3902": "spider-alt",
        "3903": "evil-moon",
        "3904": "wolf-head",
        "3905": "hunter-eyes",
        "3906": "bully-minion",
        "demo/game-icons/actor/3000.png": "https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg",
        "demo/game-icons/actor/3001.png": "https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg",
        "demo/game-icons/actor/3002.png": "https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg",
        "demo/game-icons/actor/3003.png": "https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg",
        "demo/game-icons/actor/3004.png": "https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg",
        "demo/game-icons/actor/3005.png": "https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg",
        "demo/game-icons/actor/3006.png": "https://upload.wikimedia.org/wikipedia/commons/3/3a/TheLovers.jpg",
        "demo/game-icons/actor/3007.png": "https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg",
        "demo/game-icons/actor/3008.png": "https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg",
        "demo/game-icons/actor/3009.png": "https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg"
    },
    "EquipDir": "equip/",
    "EquipMap": {
        "Z.": "",
        ".Z": ".png",
        "_": "-",
        "2101": "relic-blade",
        "2102": "heavy-arrow",
        "2103": "wizard-staff",
        "2104": "dripping-blade",
        "2105": "lightning-bow",
        "2106": "dagger-rose",
        "2107": "fairy-wand",
        "2108": "swords-emblem",
        "2109": "piercing-sword",
        "2110": "thorned-arrow",
        "2201": "gloves",
        "2202": "diamond-ring",
        "2203": "skull-ring",
        "2204": "ring",
        "2205": "globe-ring",
        "2301": "metal-skirt",
        "2302": "leather-armor",
        "2303": "heart-armor",
        "2304": "cloak",
        "2305": "spiked-armor",
        "2306": "saiyan-suit",
        "2307": "cape",
        "2401": "top-hat",
        "2402": "tiara",
        "2403": "ribbon"
    },
    "RawUnit": 1
}
